### ISSUE TITLE
Page is stating "Virtualization service (libvirt) is not active" though it is

### ISSUE THREAD

**Issue by GuiltyDoggy** [cockpit-project/cockpit-machines#1854]
Cockpit Machines page is not connecting to libvirt.
v.321-1.fc41

![Screenshot_20241010_073108](https://github.com/user-attachments/assets/0a55c9f7-adca-491e-99a5-681ebc004c75)

```
rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● fedora:fedora/41/x86_64/kinoite
                  Version: 41.20241010.n.0 (2024-10-10T08:16:03Z)
               BaseCommit: 4458d720b56080d871e2f42fa477935e564fdee0536c769cb77cac3f039cdc7e
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 131.0.2-1.fc41
          LayeredPackages: cockpit cockpit-machines cockpit-ostree cockpit-podman doas libvirt rocm-clinfo rocm-opencl rocminfo tmux vim virt-manager zsh
```
